package com.eduflow.modules.payment.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public class CheckoutRequest {

    @NotBlank(message = "Idempotency key is required")
    private String idempotencyKey; // UUID generated by the frontend

    private Boolean isSubscription = false;
    
    private Long courseId;

    private String subscriptionPeriod;

    private Boolean isGift = false;

    private String recipientName;

    private String recipientEmail;

    private String deliveryDate;

    private String giftMessage;

    private String paymentMethod;

    private String paymentDetails;

    private String couponCode;
}

