'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type LanguageType = 'English' | 'Hindi (हिन्दी)' | 'Español' | 'Deutsch' | 'Français';

interface LanguageContextProps {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// i18n Translation Dictionary mapping core UI keys to target languages
const translations: Record<LanguageType, Record<string, string>> = {
  'English': {
    'navbar.categories': 'Categories',
    'navbar.searchPlaceholder': 'Search for anything...',
    'navbar.login': 'Log in',
    'navbar.signup': 'Sign up',
    'navbar.learning': 'My Learning',
    'navbar.signout': 'Sign Out',
    'navbar.instructor': 'Instructor',
    'navbar.loading': 'Loading suggestions...',
    'navbar.noSuggestions': 'No matching courses found',
    'navbar.suggestedCourses': 'Suggested Courses',
    'navbar.matchingInstructors': 'Matching Instructors',
    'footer.sitemap': 'Sitemap',
    'footer.accessibility': 'Accessibility statement',
    'footer.cookieSettings': 'Cookie settings',
    'footer.corporate': 'Corporate Center',
    'home.heroTitle': 'Unlock Your Potential with EduFlow',
    'home.heroSubtitle': 'Master Software Engineering, Artificial Intelligence, and Quantitative Trading. Learn from industry-grade developers and build projects that stand out.',
    'home.exploreBtn': 'Explore Courses',
    'home.featuredHeading': 'Students are viewing',
    'home.browseHeading': 'Browse top categories',
    'about.welcome': 'Welcome to where possibilities begin.',
    'about.subtitle': 'About EduFlow',
    'about.creator': 'The Project Maker',
    'about.byNirav': 'Designed & Engineered by Nirav',
    'about.explore': 'Explore Catalog',
    'catalog.filters': 'Filters',
    'catalog.clearFilters': 'Clear Filters',
    'catalog.clearAll': 'Clear All',
    'catalog.sortBy': 'Sort by',
    'catalog.results': 'results',
    'catalog.ratings': 'Ratings',
    'catalog.level': 'Level',
    'catalog.topic': 'Topic',
    'catalog.language': 'Language',
    'catalog.price': 'Price',
    'catalog.andUp': '& up',
    'catalog.allLevels': 'All Levels',
    'catalog.beginner': 'Beginner',
    'catalog.intermediate': 'Intermediate',
    'catalog.expert': 'Expert',
    'catalog.paid': 'Paid',
    'catalog.free': 'Free',
    'catalog.showing': 'Showing',
    'catalog.resultsFor': 'Results for',
    'catalog.allCourses': 'All Courses',
    'contact.heading': 'Get in touch with EduFlow support',
    'contact.desc': 'Have questions about billing, account settings, or courses? Fill out the contact form below and Nirav\'s development team will assist you.',
    'contact.submit': 'Submit Message',
    'contact.sending': 'Sending message...',
    'help.heading': 'Frequently Asked Questions',
    'help.desc': 'Find instant answers to common questions about learning, streaming, and progress tracking on EduFlow.',
    'help.cta': 'Still need assistance?',
    'help.ctaDesc': 'If your question is not listed in the FAQs, please contact Nirav\'s support desk using our direct query form.',
    'help.ctaBtn': 'Go to Contact Us',
    'terms.heading': 'Terms of Use',
    'privacy.heading': 'Privacy Policy'
  },
  'Hindi (हिन्दी)': {
    'navbar.categories': 'श्रेणियाँ',
    'navbar.searchPlaceholder': 'कुछ भी खोजें...',
    'navbar.login': 'लॉग इन करें',
    'navbar.signup': 'साइन अप करें',
    'navbar.learning': 'मेरी सीख',
    'navbar.signout': 'साइन आउट',
    'navbar.instructor': 'प्रशिक्षक',
    'navbar.loading': 'सुझाव लोड हो रहे हैं...',
    'navbar.noSuggestions': 'कोई मेल खाने वाले पाठ्यक्रम नहीं मिले',
    'navbar.suggestedCourses': 'सुझाए गए पाठ्यक्रम',
    'navbar.matchingInstructors': 'मेल खाने वाले प्रशिक्षक',
    'footer.sitemap': 'साइट मैप',
    'footer.accessibility': 'पहुंच वक्तव्य',
    'footer.cookieSettings': 'कुकी सेटिंग्स',
    'footer.corporate': 'कॉर्पोरेट सेंटर',
    'home.heroTitle': 'EduFlow के साथ अपनी क्षमता को अनलॉक करें',
    'home.heroSubtitle': 'सॉफ्टवेयर इंजीनियरिंग, आर्टिफिशियल इंटेलिजेंस और क्वांटिटेटिव ट्रेडिंग में महारत हासिल करें। उद्योग-स्तर के डेवलपर्स से सीखें और उत्कृष्ट परियोजनाएं बनाएं।',
    'home.exploreBtn': 'पाठ्यक्रम देखें',
    'home.featuredHeading': 'छात्र देख रहे हैं',
    'home.browseHeading': 'शीर्ष श्रेणियां ब्राउज़ करें',
    'about.welcome': 'उस स्थान पर आपका स्वागत है जहाँ संभावनाएँ शुरू होती हैं।',
    'about.subtitle': 'EduFlow के बारे में',
    'about.creator': 'परियोजना निर्माता',
    'about.byNirav': 'नीरव द्वारा डिज़ाइन और निर्मित',
    'about.explore': 'कैटलॉग देखें',
    'catalog.filters': 'फ़िल्टर',
    'catalog.clearFilters': 'फ़िल्टर साफ करें',
    'catalog.clearAll': 'सभी साफ करें',
    'catalog.sortBy': 'क्रमबद्ध करें',
    'catalog.results': 'परिणाम',
    'catalog.ratings': 'रेटिंग्स',
    'catalog.level': 'स्तर',
    'catalog.topic': 'विषय',
    'catalog.language': 'भाषा',
    'catalog.price': 'कीमत',
    'catalog.andUp': 'और ऊपर',
    'catalog.allLevels': 'सभी स्तर',
    'catalog.beginner': 'शुरुआती',
    'catalog.intermediate': 'मध्यम',
    'catalog.expert': 'विशेषज्ञ',
    'catalog.paid': 'सशुल्क',
    'catalog.free': 'मुफ़्त',
    'catalog.showing': 'दिखा रहा है',
    'catalog.resultsFor': 'के लिए परिणाम',
    'catalog.allCourses': 'सभी पाठ्यक्रम',
    'contact.heading': 'EduFlow सहायता टीम से संपर्क करें',
    'contact.desc': 'बिलिंग, खाता सेटिंग्स या पाठ्यक्रमों के बारे में प्रश्न हैं? नीचे दिए गए संपर्क फ़ॉर्म को भरें और नीरव की विकास टीम आपकी सहायता करेगी।',
    'contact.submit': 'संदेश भेजें',
    'contact.sending': 'संदेश भेजा जा रहा है...',
    'help.heading': 'अक्सर पूछे जाने वाले प्रश्न',
    'help.desc': 'EduFlow पर सीखने, स्ट्रीमिंग और प्रगति ट्रैकिंग के बारे में सामान्य प्रश्नों के त्वरित उत्तर पाएं।',
    'help.cta': 'अभी भी सहायता की आवश्यकता है?',
    'help.ctaDesc': 'यदि आपका प्रश्न अक्सर पूछे जाने वाले प्रश्नों में सूचीबद्ध नहीं है, तो कृपया हमारे सीधे पूछताछ फ़ॉर्म का उपयोग करके नीरव के सहायता डेस्क से संपर्क करें।',
    'help.ctaBtn': 'संपर्क फ़ॉर्म पर जाएं',
    'terms.heading': 'उपयोग की शर्तें',
    'privacy.heading': 'गोपनीयता नीति'
  },
  'Español': {
    'navbar.categories': 'Categorías',
    'navbar.searchPlaceholder': 'Buscar cualquier cosa...',
    'navbar.login': 'Iniciar sesión',
    'navbar.signup': 'Registrarse',
    'navbar.learning': 'Mi aprendizaje',
    'navbar.signout': 'Cerrar sesión',
    'navbar.instructor': 'Instructor',
    'navbar.loading': 'Cargando sugerencias...',
    'navbar.noSuggestions': 'No se encontraron cursos coincidentes',
    'navbar.suggestedCourses': 'Cursos Sugeridos',
    'navbar.matchingInstructors': 'Instructores Coincidentes',
    'footer.sitemap': 'Mapa del sitio',
    'footer.accessibility': 'Declaración de accesibilidad',
    'footer.cookieSettings': 'Configuración de cookies',
    'footer.corporate': 'Centro Corporativo',
    'home.heroTitle': 'Desbloquea tu potencial con EduFlow',
    'home.heroSubtitle': 'Domine la ingeniería de software, la inteligencia artificial y el trading cuantitativo. Aprenda de desarrolladores de nivel industrial y cree proyectos que destaquen.',
    'home.exploreBtn': 'Explorar Cursos',
    'home.featuredHeading': 'Los estudiantes están viendo',
    'home.browseHeading': 'Explorar categorías principales',
    'about.welcome': 'Bienvenido a donde comienzan las posibilidades.',
    'about.subtitle': 'Sobre EduFlow',
    'about.creator': 'El Creador del Proyecto',
    'about.byNirav': 'Diseñado y Construido por Nirav',
    'about.explore': 'Explorar Catálogo',
    'catalog.filters': 'Filtros',
    'catalog.clearFilters': 'Borrar Filtros',
    'catalog.clearAll': 'Borrar Todo',
    'catalog.sortBy': 'Ordenar por',
    'catalog.results': 'resultados',
    'catalog.ratings': 'Calificaciones',
    'catalog.level': 'Nivel',
    'catalog.topic': 'Tema',
    'catalog.language': 'Idioma',
    'catalog.price': 'Precio',
    'catalog.andUp': 'y más',
    'catalog.allLevels': 'Todos los niveles',
    'catalog.beginner': 'Principiante',
    'catalog.intermediate': 'Intermedio',
    'catalog.expert': 'Experto',
    'catalog.paid': 'De pago',
    'catalog.free': 'Gratis',
    'catalog.showing': 'Mostrando',
    'catalog.resultsFor': 'Resultados para',
    'catalog.allCourses': 'Todos los Cursos',
    'contact.heading': 'Póngase en contacto con el soporte de EduFlow',
    'contact.desc': '¿Tiene preguntas sobre facturación, configuración de cuenta o cursos? Complete el formulario de contacto a continuación y el equipo de desarrollo de Nirav lo ayudará.',
    'contact.submit': 'Enviar Mensaje',
    'contact.sending': 'Enviando mensaje...',
    'help.heading': 'Preguntas Frecuentes',
    'help.desc': 'Encuentre respuestas instantáneas a preguntas comunes sobre el aprendizaje, la transmisión y el seguimiento del progreso en EduFlow.',
    'help.cta': '¿Aún necesitas ayuda?',
    'help.ctaDesc': 'Si su pregunta no aparece en las preguntas frecuentes, comuníquese con el servicio de asistencia de Nirav a través de nuestro formulario de consulta directa.',
    'help.ctaBtn': 'Ir a Contacto',
    'terms.heading': 'Términos de Uso',
    'privacy.heading': 'Política de Privacidad'
  },
  'Deutsch': {
    'navbar.categories': 'Kategorien',
    'navbar.searchPlaceholder': 'Nach allem suchen...',
    'navbar.login': 'Einloggen',
    'navbar.signup': 'Registrieren',
    'navbar.learning': 'Mein Lernen',
    'navbar.signout': 'Abmelden',
    'navbar.instructor': 'Dozent',
    'navbar.loading': 'Vorschläge werden geladen...',
    'navbar.noSuggestions': 'Keine passenden Kurse gefunden',
    'navbar.suggestedCourses': 'Empfohlene Kurse',
    'navbar.matchingInstructors': 'Passende Dozenten',
    'footer.sitemap': 'Sitemap',
    'footer.accessibility': 'Erklärung zur Barrierefreiheit',
    'footer.cookieSettings': 'Cookie-Einstellungen',
    'footer.corporate': 'Unternehmensbereich',
    'home.heroTitle': 'Schalten Sie Ihr Potenzial mit EduFlow frei',
    'home.heroSubtitle': 'Meistern Sie Software Engineering, Künstliche Intelligenz und Quantitativen Handel. Lernen Sie von branchenführenden Entwicklern und erstellen Sie herausragende Projekte.',
    'home.exploreBtn': 'Kurse Erkunden',
    'home.featuredHeading': 'Beliebte Kurse',
    'home.browseHeading': 'Top-Kategorien durchsuchen',
    'about.welcome': 'Willkommen dort, wo Möglichkeiten beginnen.',
    'about.subtitle': 'Über EduFlow',
    'about.creator': 'Der Projektentwickler',
    'about.byNirav': 'Entworfen & Entwickelt von Nirav',
    'about.explore': 'Katalog Durchsuchen',
    'catalog.filters': 'Filter',
    'catalog.clearFilters': 'Filter Löschen',
    'catalog.clearAll': 'Alles Löschen',
    'catalog.sortBy': 'Sortieren nach',
    'catalog.results': 'Ergebnisse',
    'catalog.ratings': 'Bewertungen',
    'catalog.level': 'Niveau',
    'catalog.topic': 'Thema',
    'catalog.language': 'Sprache',
    'catalog.price': 'Preis',
    'catalog.andUp': '& höher',
    'catalog.allLevels': 'Alle Niveaus',
    'catalog.beginner': 'Anfänger',
    'catalog.intermediate': 'Mittelstufe',
    'catalog.expert': 'Experte',
    'catalog.paid': 'Kostenpflichtig',
    'catalog.free': 'Kostenlos',
    'catalog.showing': 'Zeige',
    'catalog.resultsFor': 'Ergebnisse für',
    'catalog.allCourses': 'Alle Kurse',
    'contact.heading': 'EduFlow Support kontaktieren',
    'contact.desc': 'Haben Sie Fragen zu Abrechnungen, Kontoeinstellungen oder Kursen? Füllen Sie das Kontaktformular aus und das Entwicklerteam von Nirav wird Ihnen helfen.',
    'contact.submit': 'Nachricht Senden',
    'contact.sending': 'Nachricht wird gesendet...',
    'help.heading': 'Häufig gestellte Fragen',
    'help.desc': 'Finden Sie sofort Antworten auf häufige Fragen zu Lernen, Streaming und Fortschrittsverfolgung auf EduFlow.',
    'help.cta': 'Benötigen Sie noch Hilfe?',
    'help.ctaDesc': 'Wenn Ihre Frage nicht in den FAQs aufgeführt ist, kontaktieren Sie bitte den Support von Nirav über unser direktes Anfrageformular.',
    'help.ctaBtn': 'Zum Kontaktformular',
    'terms.heading': 'Nutzungsbedingungen',
    'privacy.heading': 'Datenschutzrichtlinie'
  },
  'Français': {
    'navbar.categories': 'Catégories',
    'navbar.searchPlaceholder': 'Rechercher...',
    'navbar.login': 'Se connecter',
    'navbar.signup': 'S\'inscrire',
    'navbar.learning': 'Mon apprentissage',
    'navbar.signout': 'Se déconnecter',
    'navbar.instructor': 'Formateur',
    'navbar.loading': 'Chargement des suggestions...',
    'navbar.noSuggestions': 'Aucun cours trouvé',
    'navbar.suggestedCourses': 'Cours Suggérés',
    'navbar.matchingInstructors': 'Formateurs Correspondants',
    'footer.sitemap': 'Plan du site',
    'footer.accessibility': 'Déclaration d\'accessibilité',
    'footer.cookieSettings': 'Paramètres des cookies',
    'footer.corporate': 'Espace Entreprise',
    'home.heroTitle': 'Liberez votre potentiel avec EduFlow',
    'home.heroSubtitle': 'Maîtrisez le génie logiciel, l\'intelligence artificielle et le trading quantitatif. Apprenez auprès de développeurs de niveau industriel et créez des projets qui se démarquent.',
    'home.exploreBtn': 'Explorer les Cours',
    'home.featuredHeading': 'Les étudiants consultent',
    'home.browseHeading': 'Parcourir les meilleures catégories',
    'about.welcome': 'Bienvenue là où les possibilités commencent.',
    'about.subtitle': 'À propos d\'EduFlow',
    'about.creator': 'Le Créateur du Projet',
    'about.byNirav': 'Conçu & Développé par Nirav',
    'about.explore': 'Explorer le Catalogue',
    'catalog.filters': 'Filtres',
    'catalog.clearFilters': 'Effacer les Filtres',
    'catalog.clearAll': 'Effacer Tout',
    'catalog.sortBy': 'Trier par',
    'catalog.results': 'résultats',
    'catalog.ratings': 'Évaluations',
    'catalog.level': 'Niveau',
    'catalog.topic': 'Sujet',
    'catalog.language': 'Langue',
    'catalog.price': 'Prix',
    'catalog.andUp': '& plus',
    'catalog.allLevels': 'Tous les niveaux',
    'catalog.beginner': 'Débutant',
    'catalog.intermediate': 'Intermédiaire',
    'catalog.expert': 'Expert',
    'catalog.paid': 'Payant',
    'catalog.free': 'Gratuit',
    'catalog.showing': 'Affichage de',
    'catalog.resultsFor': 'Résultats pour',
    'catalog.allCourses': 'Tous les Cours',
    'contact.heading': 'Contacter le support d\'EduFlow',
    'contact.desc': 'Des questions sur la facturation, le compte ou les cours ? Remplissez le formulaire de contact ci-dessous et l\'équipe de développement de Nirav vous aidera.',
    'contact.submit': 'Envoyer le Message',
    'contact.sending': 'Envoi en cours...',
    'help.heading': 'Questions Fréquentes',
    'help.desc': 'Trouvez des réponses instantanées aux questions courantes sur l\'apprentissage, le streaming et le suivi de progression sur EduFlow.',
    'help.cta': 'Besoin d\'aide supplémentaire ?',
    'help.ctaDesc': 'Si votre question n\'est pas répertoriée dans la FAQ, veuillez contacter le service d\'assistance de Nirav via notre formulaire de contact direct.',
    'help.ctaBtn': 'Aller au Contact',
    'terms.heading': 'Conditions d\'Utilisation',
    'privacy.heading': 'Politique de Confidentialité'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageType>('English');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('eduflow_lang');
    if (saved && Object.keys(translations).includes(saved)) {
      setLanguageState(saved as LanguageType);
    }
  }, []);

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem('eduflow_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations['English']?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
