-- Add type column to courses table
ALTER TABLE courses ADD COLUMN type VARCHAR(50) DEFAULT 'COURSE' NOT NULL;

-- Create Practice Questions Table
CREATE TABLE practice_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option VARCHAR(5) NOT NULL, -- 'A', 'B', 'C', 'D'
    explanation TEXT,
    CONSTRAINT fk_questions_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- Create Practice Test Attempts Table
CREATE TABLE practice_test_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    passed BOOLEAN NOT NULL,
    attempted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_attempts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_attempts_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- Performance Indexes
CREATE INDEX idx_practice_questions_course_id ON practice_questions(course_id);
CREATE INDEX idx_practice_test_attempts_user_id ON practice_test_attempts(user_id);
CREATE INDEX idx_practice_test_attempts_course_id ON practice_test_attempts(course_id);
